project:
  name: cupidcrew
  version: 1.0

server:
  port: 1111
  tomcat:
    max-http-form-post-size: 100MB

spring:
  security:
    user:
      name: "admin"
      password: "zofht11!!"
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url : jdbc:mariadb://0.0.0.0:3306/cupidcrew?createDatabaseIfNotExist=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: zofht11!!
#    url : jdbc:mariadb://localhost:3306/cupidcrew?createDatabaseIfNotExist=true
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password: 1234
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MariaDB103Dialect
      show_sql: true
      format_sql: true
      use_sql_comments: true
      ddl-auto: update # create, update, validate
  springdoc:
    swagger-ui:
      tryItOutEnabled: true
      docExpansion: none
      tagsSorter: alpha
      operationsSorter: alpha

minio:
  url: http://localhost:9000
  accessKey: ivy
  secretKey: 123456789
  bucketName: candidates

#logging:
#  config: src/main/resources/log4j2.yaml