project:
  name: cupidcrew
  version: 1.0
  domain: http://localhost:8080

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/cupidcrew
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MariaDB103Dialect
      show_sql: true
      format_sql: true
      use_sql_comments: true
      ddl-auto: create # create, update, validate
  springdoc:
    swagger-ui:
      tryItOutEnabled: true
      docExpansion: none
      tagsSorter: alpha
      operationsSorter: alpha
#      path: /swagger-ui



#logging:
#  config: src/main/resources/log4j2.yaml