project:
  name: cupidcrew
  version: 1.0
  domain: http://localhost:8080

server:
  port: 8080

spring:
#  datasource:
#    url: jdbc:h2:mem:cupidcrew
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  datasource:
#    url: jdbc:mariadb://localhost:3306/cupidcrew
    url : jdbc:mariadb://0.0.0.0:3306/cupidcrew
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
#  h2:
#    console:
#      enabled: true # H2 데이터베이스 콘솔을 활성화
#      path: /h2-console
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MariaDB103Dialect
      show_sql: true
      format_sql: true
      use_sql_comments: true
      ddl-auto: update # create, update, validate
  springdoc:
    swagger-ui:
      tryItOutEnabled: true
      docExpansion: none
      tagsSorter: alpha
      operationsSorter: alpha
#      path: /swagger-ui



#logging:
#  config: src/main/resources/log4j2.yaml